CREATE DATABASE IF NOT EXISTS fitness;

USE fitness;

CREATE TABLE IF NOT EXISTS User (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  isAdmin BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS Exercise (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    exerciseName VARCHAR (255) NOT NULL,
    sets INT NULL, 
    repetitions INT NULL
);

CREATE TABLE IF NOT EXISTS Workout (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR (30) NOT NULL,
    duration VARCHAR(30) NULL
);